const SWITCH_PAGE = `SWITCH_PAGE`;
const FETCH_PRODUCTS = `FETCH_PRODUCTS`;
const SORT_PRODUCTS = `SORT_PRODUCTS`;
const FAVORITES_ADD = `FAVORITES_ADD`;
const CART_ADD = `CART_ADD`;

export {
  SWITCH_PAGE,
  FETCH_PRODUCTS,
  SORT_PRODUCTS,
  FAVORITES_ADD,
  CART_ADD
};
