enum Actions {
  SWITCH_PAGE = `SWITCH_PAGE`,
  FETCH_PRODUCTS = `FETCH_PRODUCTS`,
  SORT_PRODUCTS = `SORT_PRODUCTS`,
  FAVORITES_ADD = `FAVORITES_ADD`,
  CART_ADD = `CART_ADD`
}

export {
  Actions
};
